name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Debug - Print pnpm version
        run: pnpm --version

      - name: Debug - Print Git core config
        run: |
          echo "--- Git Config ---"
          git config --list
          echo "------------------"

      - name: Debug - Print package.json content
        run: |
          echo "--- package.json ---"
          cat package.json
          echo "--------------------"

      - name: Debug - Print pnpm-lock.yaml content
        run: |
          echo "--- pnpm-lock.yaml ---"
          cat pnpm-lock.yaml
          echo "----------------------"

      - name: Debug - List patches directory content
        run: |
          echo "--- patches/ content ---"
          ls -la patches/
          echo "------------------------"

      - name: Debug - Print patch file content and calculate hash on CI runner
        run: |
          PATCH_FILE="patches/vite-plugin-svg-icons-ng@1.4.0.patch" # 确保文件名正确
          echo "--- Content of $PATCH_FILE on CI ---"
          cat "$PATCH_FILE"
          echo "------------------------------------"
          echo "--- Calculating SHA1 hash of $PATCH_FILE on CI ---"
          # pnpm lock file hash starting with 7h... is base32 encoded SHA1 hash (20 bytes)
          # Use sha1sum and then potentially convert or compare byte representation if needed, but simple comparison might reveal difference.
          sha1sum "$PATCH_FILE"
          echo "--------------------------------------------------"

      - name: Debug - Check Git index content on CI runner
        run: |
          echo "--- Git Index Content (from object db) ---"
          git cat-file -p HEAD:patches/vite-plugin-svg-icons-ng@1.4.0.patch
          echo "-----------------------------------------"

      - name: Debug - Check patch file line endings on CI runner filesystem
        run: |
          PATCH_FILE="patches/vite-plugin-svg-icons-ng@1.4.0.patch"
          echo "--- Checking file on filesystem: $PATCH_FILE ---"
          # 使用 file 命令检查文件类型 (应为 ASCII text)
          file "$PATCH_FILE"
          # 使用 cat -v 显示非打印字符，^M 表示 CR
          echo "--- Content with visible control chars ---"
          cat -v "$PATCH_FILE"
          echo "------------------------------------------"
          # 再次计算哈希
          echo "--- Recalculating SHA1 hash of file on filesystem ---"
          sha1sum "$PATCH_FILE"
          echo "-----------------------------------------------------"

      - name: Install dependencies
        run: pnpm install

      - name: Build step
        run: "pnpm build"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "eykettle-manual"
          entrypoint: "main.ts"
          root: "dist"
          
          
